### PR TITLE
add new plusargs for control of obi vip configs for delay configurations

### PR DESCRIPTION
**Pull request by dd-vaibhavjain**

### CODE REVIEW

**Comment by dd-baoshan** [comment]
testing

**Review by dd-baoshan — COMMENTED** [review]
1) constraints
	- for random_* constraint (e.g random_data_stall_sim_cons), we need to check what is the default setting of min and max (should we define explicitely?)
	- for long_random_* constraint (e.g long_random_data_stall_sim_cons), maybe we can set the min limit to "random_* constraint max setting + 1" and max limit to min + 8. this can prevent overlap of min-max of random_* versus long_random_*
	
2) line 450-470
	- the plusargs have priority due to if..elsif statement. IS it better to put assert statement to trigger error message to user if they accidently set multiple plusargs?
	- fixed_data_stall  and  fixed_data_rvalid_stall are doing similar (both set on rvalid latency) ?
	- fixed_data_gnt_stall and fixed_data_rvalid_stall have no dependency, does it means users should be allowed to insert multiple plusargs to enable both of them ?

**Comment by dd-vaibhavjain** [comment]
> 1. constraints
>    
>    * for random_* constraint (e.g random_data_stall_sim_cons), we need to check what is the default setting of min and max (should we define explicitely?)

Present random delay constraints : (these are base constraints applicable unless overriden)   
soft obi_memory_instr_cfg.drv_slv_gnt_random_latency_max    <= 2;  
soft obi_memory_instr_cfg.drv_slv_gnt_fixed_latency         <= 2;  
soft obi_memory_instr_cfg.drv_slv_rvalid_random_latency_max <= 3;  
soft obi_memory_instr_cfg.drv_slv_rvalid_fixed_latency      <= 3;  

Yes we can also make it similar to other constraints and allow specific value from plusargs. - taken an **Action Item.**



>    * for long_random_* constraint (e.g long_random_data_stall_sim_cons), maybe we can set the min limit to "random_* constraint max setting + 1" and max limit to min + 8. this can prevent overlap of min-max of random_* versus long_random_*

The intention is to have random delay upto a certain bigger value, instead of _only_ bigger values. Having a bigger range is good as it will excersice all cases , for example, cases such as 0 delay followed by max delay. Running regressions with this config should create sufficient coverage for many cases.  



> 2. line 450-470
>    
>    * the plusargs have priority due to if..elsif statement. IS it better to put assert statement to trigger error message to user if they accidently set multiple plusargs?

Yes good point. I though had thought about it and intentionally did not provide any errors at the moment since the if-else will take care of priority and obi coverage will tell if we are exercising some things.
Maybe rather than _fatal_ errors, we should think of adding some more functional coverage.
Also the regression script is expected to be created with the knowledge of these items and specified in Test plans.


>    * fixed_data_stall  and  fixed_data_rvalid_stall are doing similar (both set on rvalid latency) ?

fixed data stall sets the gnt delay to 0, whereas the fixed_data_rvalid_stall provides further granularity to use only rvalid constraints, it will leave the gnt constraints to be left to common constraints.

>    * fixed_data_gnt_stall and fixed_data_rvalid_stall have no dependency, it means users should allow to insert multiple plusargs to enable both of them ?

Yes good point. I should update the constraints to allow both to be allowed together - taken **Action Item**

**Comment by dd-vaibhavjain** [comment]
@dd-baoshan I have pushed updates for 2 action items above

**Comment by XavierAubert** [comment]
I went through the PR, it looks good to me, I think we should have enough control with these modifications

**Pull request merged**
