### PR TITLE
Add stream test to check on fs state transisition from Initial/CLean …

### PR DESCRIPTION
**Pull request by dd-baoshan**
[quoted from Pascal] 
After the sequence initialization, FS should be put back to either Clean or Initial state.
test all FS transitions.
And by each different classes of instructions (move, compare, computing, load, stores...).

@XavierAubert , as per communication, you will draft the testplan. AS such, I put you as reviewer.

### CODE REVIEW

**Comment by dd-vaibhavjain** [comment]
Apologies for getting in this conversation without being asked.
But i just want to re-emphasize that there is a need for mstatus test that is **self checking** . It could be random for the instruction it excersizes each time, but there needs to be a front door access to determine exact CSR status. There is a SD bit as well.
Plus due to the way RVFI is, I would not trust the results if they were as not confirmed by a front door access.

**Comment by dd-baoshan** [comment]
> Apologies for getting in this conversation without being asked. But i just want to re-emphasize that there is a need for mstatus test that is **self checking** . It could be random for the instruction it excersizes each time, but there needs to be a front door access to determine exact CSR status. There is a SD bit as well. Plus due to the way RVFI is, I would not trust the results if they were as not confirmed by a front door access.

Thanks for the Inputs. Let me think about this.
@xau, please consider this as part of the testplan.

**Comment by dd-baoshan** [comment]
@dd-vaibhavjain , @XavierAubert 
I have added fixmes. one of them is related to mstatus frontdoor selfcheck. Currently I am working on some other stuff, I will back to this fixme soon. 
Pascal need this test to check-in his rtl fixes that related to flw, therefore I need @XavierAubert to merge this and PR to openhwgroup for Pascal to access.

**Comment by dd-vaibhavjain** [comment]
If this is urgent then can be done directly in cv32e40p/dev. Also I feel this needs a separate test. If this is temporary then also no point to put it in OHG issue ticket.

**Comment by XavierAubert** [comment]
Ok, sure I can merge the PR to dev_dd, but could Pascal just use dev_dd instead of pushing to OHG ? I will check with him

**Pull request merged**
