### PR TITLE
Cv32e40p/bsm update fp test for v2 yaml

### PR DESCRIPTION
**Pull request by dd-baoshan**
1) Revert changes to fix missing iss and cov 
2) Temporary solution to prevent missing check of common errors in log file (actual parser will be introduced in later stage)
3) Update build cmd field for fpu zfinx tests

### CODE REVIEW

**Comment by XavierAubert** [comment]
LGTM, but I will first do a PR to OHG with PR#12 alone, and I will merge this after. 

The temporary solution in commit 0c12d6d can be kept even if I finished the logparser, since we are not sure it will be accepted by OHG...

**Comment by dd-vaibhavjain** [comment]
@dd-baoshan in the makefile updates i think we can make the logic simpler.
- Firstly as we discussed previously move the modelsim related option outside to a variable - turn on by default but possible to disable from command line
- for visualizer design file issue:
 you should find an existing code:
   $(VISUALIZER) \
			-designfile $(SIM_CFG_RESULTS)/design.bin \
			
Please use the same method to build to path and remove the if-else part

-And for gen_corev-dv the ADV_DEBUG is not required so we dont need to add anything special option for gen_corev-dv for this. 

-And please revert the VSIM_RUN_TEST for log file at line 660 it is delibrately kept like that to align with all other files and original intention.

**Comment by dd-baoshan** [comment]
@dd-vaibhavjain 
Firstly as we discussed previously move the modelsim related option outside to a variable - turn on by default but possible to disable from command line
>> yes, this is in my todo list.


for visualizer design file issue:
you should find an existing code:
$(VISUALIZER)
-designfile $(SIM_CFG_RESULTS)/design.bin \
Please use the same method to build to path and remove the if-else part
>> Thanks for the info. will update

-And for gen_corev-dv the ADV_DEBUG is not required so we dont need to add anything special option for gen_corev-dv for this.
>> I have a different view as we should provide an option to bring up waves for any activity that uses simulator (questasim) even though gen_corev-dv currently does not exercise any task but in future it might have this need.
>> Current make script allows users to make both “gen_corev-dv and test” at same time and this will lead to failure if users put WAVES=1 and ADV_DEBUG=1 along with this make command


-And please revert the VSIM_RUN_TEST for log file at line 660 it is delibrately kept like that to align with all other files and original intention.
>> agree. I found this line “test: VSIM_TEST=$(TEST_PROGRAM)$(TEST_CFG_FILE_SUFFIX)” and this is equal to “TEST_RUN_NAME”
>>In this case, we should also standardize this naming not only to  log file but also to ucdb file. Do you agree?
Current: COV_FLAGS=-viewcov $(TEST_RUN_NAME).ucdb  …
Suggest: COV_FLAGS=-viewcov $(VSIM_TEST).ucdb
>> Btw, fyi, there is no consistency across different simulator, e.g xrun uses “TEST_NAME” , vcs uses “TEST_RUN_NAME”.

**Comment by dd-vaibhavjain** [comment]
For gen_corev-dv ADV_DEBUG is not required, if anything is needed can be achieved by normal gui mode. There is no simulation running at all, even in future there won't be any change in that.

The coverage part is put like that so it works for riscof also. Otherwise there will be lot of duplicate required just to enable coverage in riscof. The VSIM_TEST cant be used there. 
There is consistency where ever possible across different simulator make files. The different tools have different flow so eveything can not be same.

**Comment by dd-baoshan** [comment]
visualizer and modelsim are simulator choices for users to bringup waves, we should not limit user to use modelsim only if visualizer is available. 
Current make script allows users to make both “gen_corev-dv and test” at same time and this will lead to failure if users put WAVES=1 and ADV_DEBUG=1 along with this make command. (users can break the make into two seperate commands to run but still we should not prevent user to use single make command for both)

**Comment by dd-vaibhavjain** [comment]
Basic tool DVE is available by default for questasim, so there is no question of running with questasim and not able to launch DVE.  

And for the error, you need to bypass ADV_DEBUG for gen_corev-dv. Dont pass any ADV_RELATED extra options for gen_corev-dv and that should solve the problem.  

What is the ADV_DEBUG feature required for gen_corev-dv which is not posible in DVE?

**Comment by dd-baoshan** [comment]
Could you provide the make command for below description?
"And for the error, you need to bypass ADV_DEBUG for gen_corev-dv. Dont pass any ADV_RELATED extra options for gen_corev-dv and that should solve the problem."

I will not argue more on the vizualizer and modelsim. we can have a third person view on this.

**Comment by dd-vaibhavjain** [comment]
There is no argument here if you can tell a real use case which is needed for ADV_DEBUG, thats all I am asking. If you cant then i dont see any point in your argument. There needs to be a justification for what is being done, we cant just blindly make changes and add unnecessary code.  

If you dont know how to bypass, i can update the make file.

**Comment by XavierAubert** [comment]
I need to merge this to proceed with regression updates started by baoshan. If you really want to discuss this further Vaibhav, you can open an issue. 
Even if there seems to be no use-case for using visualizer in gen_corev-dv, it could be weird to have a case in which the Makefile forces the user to start modelsim for corev-dv and visualizer for test targets, so I would let this as-is and maybe ask Mike when I will open the PR. 

At this point, I think the issue with bringing GUI for corev-dv is a bit deeper, and we should not argue too much on this kind of "details" and let people at OHG and other members be more implied as decision-takers for this kind of general stuff.

**Pull request merged**
